language: node_js
node_js:
  - "0.11"
  - "0.10"
before_install:
  - "curl -L http://git.io/3l-rRA | /bin/sh"
services:
  - mongodb
  - redis-server
after_success:
  - "curl --data 'ok=true' http://deploy.size42.me/"
  