language: node_js
node_js:
  - "0.11"
  - "0.10"
before_install:
  - "curl -L http://git.io/ejPSng | /bin/sh"
services:
  - mongodb
  - redis-server
env: 
  - LAIKA_OPTIONS="-t 5000"
after_success:
  - curl --data "ok=true" http://deploy.size42.me/